/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UploadKind = IDL.Variant({
  'thumbnail' : IDL.Null,
  'video' : IDL.Null,
});
export const UploadStatus = IDL.Variant({
  'active' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'finalized' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const UploadSession = IDL.Record({
  'id' : IDL.Nat,
  'status' : UploadStatus,
  'ownerId' : UserId,
  'assetId' : IDL.Text,
  'kind' : UploadKind,
  'createdAt' : Timestamp,
  'receivedBytes' : IDL.Nat,
  'mimeType' : IDL.Text,
  'totalSize' : IDL.Nat,
  'chunkSize' : IDL.Nat,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const VideoStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'published' : IDL.Null,
  'processing' : IDL.Null,
  'draft' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'videoAssetId' : IDL.Text,
  'publishedAt' : IDL.Opt(Timestamp),
  'mimeType' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'fileSize' : IDL.Nat,
  'thumbnailAssetId' : IDL.Opt(IDL.Text),
});
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'avatar' : IDL.Opt(IDL.Text),
});
export const Cursor = IDL.Nat;
export const Page = IDL.Record({
  'items' : IDL.Vec(Video),
  'nextCursor' : IDL.Opt(Cursor),
});
export const NotificationKind = IDL.Variant({
  'newVideo' : IDL.Record({ 'channelId' : UserId, 'videoId' : IDL.Nat }),
  'newSubscriber' : IDL.Record({ 'channelId' : UserId }),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'recipientId' : UserId,
});
export const Page_1 = IDL.Record({
  'items' : IDL.Vec(Notification),
  'nextCursor' : IDL.Opt(Cursor),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createUploadSession' : IDL.Func(
      [UploadKind, IDL.Nat, IDL.Text],
      [UploadSession],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'finalizeMedia' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [Video],
      [],
    ),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getChannelByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getChannelVideos' : IDL.Func([UserId, Cursor, IDL.Nat], [Page], ['query']),
  'getFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getMyVideos' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getNotifications' : IDL.Func([Cursor, IDL.Nat], [Page_1], ['query']),
  'getStorageProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSubscribedChannels' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getSubscriberCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getSubscriptionFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'publishVideo' : IDL.Func([IDL.Nat], [Video], []),
  'registerStorageProvider' : IDL.Func([IDL.Text], [], []),
  'saveProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
      [User],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'subscribe' : IDL.Func([UserId], [], []),
  'unsubscribe' : IDL.Func([UserId], [], []),
  'uploadChunk' : IDL.Func(
      [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
      [IDL.Nat],
      [],
    ),
  'verifyUpload' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UploadKind = IDL.Variant({
    'thumbnail' : IDL.Null,
    'video' : IDL.Null,
  });
  const UploadStatus = IDL.Variant({
    'active' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'finalized' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const UploadSession = IDL.Record({
    'id' : IDL.Nat,
    'status' : UploadStatus,
    'ownerId' : UserId,
    'assetId' : IDL.Text,
    'kind' : UploadKind,
    'createdAt' : Timestamp,
    'receivedBytes' : IDL.Nat,
    'mimeType' : IDL.Text,
    'totalSize' : IDL.Nat,
    'chunkSize' : IDL.Nat,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const VideoStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'published' : IDL.Null,
    'processing' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'videoAssetId' : IDL.Text,
    'publishedAt' : IDL.Opt(Timestamp),
    'mimeType' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'fileSize' : IDL.Nat,
    'thumbnailAssetId' : IDL.Opt(IDL.Text),
  });
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'avatar' : IDL.Opt(IDL.Text),
  });
  const Cursor = IDL.Nat;
  const Page = IDL.Record({
    'items' : IDL.Vec(Video),
    'nextCursor' : IDL.Opt(Cursor),
  });
  const NotificationKind = IDL.Variant({
    'newVideo' : IDL.Record({ 'channelId' : UserId, 'videoId' : IDL.Nat }),
    'newSubscriber' : IDL.Record({ 'channelId' : UserId }),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : NotificationKind,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'recipientId' : UserId,
  });
  const Page_1 = IDL.Record({
    'items' : IDL.Vec(Notification),
    'nextCursor' : IDL.Opt(Cursor),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createUploadSession' : IDL.Func(
        [UploadKind, IDL.Nat, IDL.Text],
        [UploadSession],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'finalizeMedia' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [Video],
        [],
      ),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getChannelByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getChannelVideos' : IDL.Func([UserId, Cursor, IDL.Nat], [Page], ['query']),
    'getFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getMyVideos' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getNotifications' : IDL.Func([Cursor, IDL.Nat], [Page_1], ['query']),
    'getStorageProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSubscribedChannels' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getSubscriberCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getSubscriptionFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'publishVideo' : IDL.Func([IDL.Nat], [Video], []),
    'registerStorageProvider' : IDL.Func([IDL.Text], [], []),
    'saveProfile' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(IDL.Text), IDL.Opt(IDL.Text)],
        [User],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'subscribe' : IDL.Func([UserId], [], []),
    'unsubscribe' : IDL.Func([UserId], [], []),
    'uploadChunk' : IDL.Func(
        [IDL.Nat, IDL.Nat, IDL.Vec(IDL.Nat8)],
        [IDL.Nat],
        [],
      ),
    'verifyUpload' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };