/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Playlist = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'isPrivate' : IDL.Bool,
  'videoIds' : IDL.Vec(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const PlaylistSelection = IDL.Variant({
  'new' : IDL.Record({ 'title' : IDL.Text, 'isPrivate' : IDL.Bool }),
  'existing' : IDL.Nat,
});
export const VideoStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'published' : IDL.Null,
  'processing' : IDL.Null,
  'draft' : IDL.Null,
});
export const Video = IDL.Record({
  'id' : IDL.Nat,
  'status' : VideoStatus,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'ownerId' : UserId,
  'video' : ExternalBlob,
  'createdAt' : Timestamp,
  'publishedAt' : IDL.Opt(Timestamp),
  'mimeType' : IDL.Text,
  'description' : IDL.Opt(IDL.Text),
  'fileSize' : IDL.Nat,
  'filename' : IDL.Text,
  'viewCount' : IDL.Nat,
  'isPrivate' : IDL.Bool,
});
export const CreateVideoResult = IDL.Record({
  'video' : Video,
  'playlistId' : IDL.Opt(IDL.Nat),
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const User = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'displayName' : IDL.Text,
  'createdAt' : Timestamp,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Cursor = IDL.Nat;
export const PlaylistSummary = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'thumbnail' : IDL.Opt(ExternalBlob),
  'videoCount' : IDL.Nat,
  'firstVideoId' : IDL.Opt(IDL.Nat),
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'updatedAt' : Timestamp,
  'isPrivate' : IDL.Bool,
});
export const Page_2 = IDL.Record({
  'items' : IDL.Vec(PlaylistSummary),
  'nextCursor' : IDL.Opt(Cursor),
});
export const Page = IDL.Record({
  'items' : IDL.Vec(Video),
  'nextCursor' : IDL.Opt(Cursor),
});
export const NotificationKind = IDL.Variant({
  'newVideo' : IDL.Record({ 'channelId' : UserId, 'videoId' : IDL.Nat }),
  'newSubscriber' : IDL.Record({ 'channelId' : UserId }),
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
  'recipientId' : UserId,
});
export const Page_1 = IDL.Record({
  'items' : IDL.Vec(Notification),
  'nextCursor' : IDL.Opt(Cursor),
});
export const PlaylistView = IDL.Record({
  'playlist' : PlaylistSummary,
  'videos' : IDL.Vec(Video),
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addVideoToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [Playlist], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createPlaylist' : IDL.Func(
      [IDL.Text, IDL.Bool, IDL.Opt(IDL.Nat)],
      [Playlist],
      [],
    ),
  'createVideo' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        ExternalBlob,
        IDL.Opt(ExternalBlob),
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Bool,
        IDL.Opt(PlaylistSelection),
      ],
      [CreateVideoResult],
      [],
    ),
  'deleteVideo' : IDL.Func([IDL.Nat], [], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getChannel' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
  'getChannelByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
  'getChannelPlaylists' : IDL.Func(
      [UserId, Cursor, IDL.Nat],
      [Page_2],
      ['query'],
    ),
  'getChannelVideos' : IDL.Func([UserId, Cursor, IDL.Nat], [Page], ['query']),
  'getFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
  'getMyVideos' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getNotifications' : IDL.Func([Cursor, IDL.Nat], [Page_1], ['query']),
  'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(PlaylistView)], ['query']),
  'getStorageProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'getSubscribedChannels' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
  'getSubscriberCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
  'getSubscriptionFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isSubscribed' : IDL.Func([UserId], [IDL.Bool], ['query']),
  'markNotificationsRead' : IDL.Func([], [], []),
  'publishVideo' : IDL.Func([IDL.Nat], [Video], []),
  'recordVideoView' : IDL.Func([IDL.Nat], [IDL.Nat], []),
  'registerStorageProvider' : IDL.Func([IDL.Text], [], []),
  'removeVideoFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [Playlist], []),
  'saveProfile' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Opt(ExternalBlob), IDL.Bool, IDL.Opt(IDL.Text)],
      [User],
      [],
    ),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'subscribe' : IDL.Func([UserId], [], []),
  'unsubscribe' : IDL.Func([UserId], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Playlist = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'isPrivate' : IDL.Bool,
    'videoIds' : IDL.Vec(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const PlaylistSelection = IDL.Variant({
    'new' : IDL.Record({ 'title' : IDL.Text, 'isPrivate' : IDL.Bool }),
    'existing' : IDL.Nat,
  });
  const VideoStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'published' : IDL.Null,
    'processing' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Video = IDL.Record({
    'id' : IDL.Nat,
    'status' : VideoStatus,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'ownerId' : UserId,
    'video' : ExternalBlob,
    'createdAt' : Timestamp,
    'publishedAt' : IDL.Opt(Timestamp),
    'mimeType' : IDL.Text,
    'description' : IDL.Opt(IDL.Text),
    'fileSize' : IDL.Nat,
    'filename' : IDL.Text,
    'viewCount' : IDL.Nat,
    'isPrivate' : IDL.Bool,
  });
  const CreateVideoResult = IDL.Record({
    'video' : Video,
    'playlistId' : IDL.Opt(IDL.Nat),
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const User = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'displayName' : IDL.Text,
    'createdAt' : Timestamp,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Cursor = IDL.Nat;
  const PlaylistSummary = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'thumbnail' : IDL.Opt(ExternalBlob),
    'videoCount' : IDL.Nat,
    'firstVideoId' : IDL.Opt(IDL.Nat),
    'ownerId' : UserId,
    'createdAt' : Timestamp,
    'updatedAt' : Timestamp,
    'isPrivate' : IDL.Bool,
  });
  const Page_2 = IDL.Record({
    'items' : IDL.Vec(PlaylistSummary),
    'nextCursor' : IDL.Opt(Cursor),
  });
  const Page = IDL.Record({
    'items' : IDL.Vec(Video),
    'nextCursor' : IDL.Opt(Cursor),
  });
  const NotificationKind = IDL.Variant({
    'newVideo' : IDL.Record({ 'channelId' : UserId, 'videoId' : IDL.Nat }),
    'newSubscriber' : IDL.Record({ 'channelId' : UserId }),
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'kind' : NotificationKind,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
    'recipientId' : UserId,
  });
  const Page_1 = IDL.Record({
    'items' : IDL.Vec(Notification),
    'nextCursor' : IDL.Opt(Cursor),
  });
  const PlaylistView = IDL.Record({
    'playlist' : PlaylistSummary,
    'videos' : IDL.Vec(Video),
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addVideoToPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [Playlist], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createPlaylist' : IDL.Func(
        [IDL.Text, IDL.Bool, IDL.Opt(IDL.Nat)],
        [Playlist],
        [],
      ),
    'createVideo' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          ExternalBlob,
          IDL.Opt(ExternalBlob),
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Bool,
          IDL.Opt(PlaylistSelection),
        ],
        [CreateVideoResult],
        [],
      ),
    'deleteVideo' : IDL.Func([IDL.Nat], [], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerProfile' : IDL.Func([], [IDL.Opt(User)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getChannel' : IDL.Func([UserId], [IDL.Opt(User)], ['query']),
    'getChannelByUsername' : IDL.Func([IDL.Text], [IDL.Opt(User)], ['query']),
    'getChannelPlaylists' : IDL.Func(
        [UserId, Cursor, IDL.Nat],
        [Page_2],
        ['query'],
      ),
    'getChannelVideos' : IDL.Func([UserId, Cursor, IDL.Nat], [Page], ['query']),
    'getFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getMyPlaylists' : IDL.Func([], [IDL.Vec(Playlist)], ['query']),
    'getMyVideos' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getNotifications' : IDL.Func([Cursor, IDL.Nat], [Page_1], ['query']),
    'getPlaylist' : IDL.Func([IDL.Nat], [IDL.Opt(PlaylistView)], ['query']),
    'getStorageProviders' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'getSubscribedChannels' : IDL.Func([], [IDL.Vec(UserId)], ['query']),
    'getSubscriberCount' : IDL.Func([UserId], [IDL.Nat], ['query']),
    'getSubscriptionFeed' : IDL.Func([Cursor, IDL.Nat], [Page], ['query']),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getVideo' : IDL.Func([IDL.Nat], [IDL.Opt(Video)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isSubscribed' : IDL.Func([UserId], [IDL.Bool], ['query']),
    'markNotificationsRead' : IDL.Func([], [], []),
    'publishVideo' : IDL.Func([IDL.Nat], [Video], []),
    'recordVideoView' : IDL.Func([IDL.Nat], [IDL.Nat], []),
    'registerStorageProvider' : IDL.Func([IDL.Text], [], []),
    'removeVideoFromPlaylist' : IDL.Func([IDL.Nat, IDL.Nat], [Playlist], []),
    'saveProfile' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Opt(ExternalBlob),
          IDL.Bool,
          IDL.Opt(IDL.Text),
        ],
        [User],
        [],
      ),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'subscribe' : IDL.Func([UserId], [], []),
    'unsubscribe' : IDL.Func([UserId], [], []),
  });
};

export const init = ({ IDL }) => { return []; };