/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Cell { 'value' : Value, 'name' : string }
export type Cursor = bigint;
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface Notification {
  'id' : bigint,
  'kind' : NotificationKind,
  'createdAt' : Timestamp,
  'read' : boolean,
  'recipientId' : UserId,
}
export type NotificationKind = {
    'newVideo' : { 'channelId' : UserId, 'videoId' : bigint }
  } |
  { 'newSubscriber' : { 'channelId' : UserId } };
export interface Page { 'items' : Array<Video>, 'nextCursor' : [] | [Cursor] }
export interface Page_1 {
  'items' : Array<Notification>,
  'nextCursor' : [] | [Cursor],
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export type Timestamp = bigint;
export type UploadKind = { 'thumbnail' : null } |
  { 'video' : null };
export interface UploadSession {
  'id' : bigint,
  'status' : UploadStatus,
  'ownerId' : UserId,
  'assetId' : string,
  'kind' : UploadKind,
  'createdAt' : Timestamp,
  'receivedBytes' : bigint,
  'mimeType' : string,
  'totalSize' : bigint,
  'chunkSize' : bigint,
}
export type UploadStatus = { 'active' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'finalized' : null };
export interface User {
  'id' : UserId,
  'bio' : [] | [string],
  'username' : string,
  'displayName' : string,
  'createdAt' : Timestamp,
  'avatar' : [] | [string],
}
export type UserId = Principal;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface Video {
  'id' : bigint,
  'status' : VideoStatus,
  'title' : string,
  'ownerId' : UserId,
  'createdAt' : Timestamp,
  'videoAssetId' : string,
  'publishedAt' : [] | [Timestamp],
  'mimeType' : string,
  'description' : [] | [string],
  'fileSize' : bigint,
  'thumbnailAssetId' : [] | [string],
}
export type VideoStatus = { 'deleted' : null } |
  { 'published' : null } |
  { 'processing' : null } |
  { 'draft' : null };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createUploadSession' : ActorMethod<
    [UploadKind, bigint, string],
    UploadSession
  >,
  'deleteVideo' : ActorMethod<[bigint], undefined>,
  'execute' : ActorMethod<[string], Result>,
  'finalizeMedia' : ActorMethod<
    [bigint, string, [] | [string], [] | [string]],
    Video
  >,
  'getApiDoc' : ActorMethod<[], string>,
  'getCallerProfile' : ActorMethod<[], [] | [User]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getChannel' : ActorMethod<[UserId], [] | [User]>,
  'getChannelByUsername' : ActorMethod<[string], [] | [User]>,
  'getChannelVideos' : ActorMethod<[UserId, Cursor, bigint], Page>,
  'getFeed' : ActorMethod<[Cursor, bigint], Page>,
  'getMyVideos' : ActorMethod<[Cursor, bigint], Page>,
  'getNotifications' : ActorMethod<[Cursor, bigint], Page_1>,
  'getStorageProviders' : ActorMethod<[], Array<string>>,
  'getSubscribedChannels' : ActorMethod<[], Array<UserId>>,
  'getSubscriberCount' : ActorMethod<[UserId], bigint>,
  'getSubscriptionFeed' : ActorMethod<[Cursor, bigint], Page>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getVideo' : ActorMethod<[bigint], [] | [Video]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isSubscribed' : ActorMethod<[UserId], boolean>,
  'markNotificationsRead' : ActorMethod<[], undefined>,
  'publishVideo' : ActorMethod<[bigint], Video>,
  'registerStorageProvider' : ActorMethod<[string], undefined>,
  'saveProfile' : ActorMethod<
    [string, string, [] | [string], [] | [string]],
    User
  >,
  'schema' : ActorMethod<[], string>,
  'subscribe' : ActorMethod<[UserId], undefined>,
  'unsubscribe' : ActorMethod<[UserId], undefined>,
  'uploadChunk' : ActorMethod<[bigint, bigint, Uint8Array], bigint>,
  'verifyUpload' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];