/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Video {
    id: bigint;
    status: VideoStatus;
    title: string;
    thumbnail?: ExternalBlob;
    ownerId: UserId;
    video: ExternalBlob;
    createdAt: Timestamp;
    publishedAt?: Timestamp;
    mimeType: string;
    description?: string;
    fileSize: bigint;
    filename: string;
    viewCount: bigint;
    isPrivate: boolean;
}
export type Timestamp = bigint;
export interface PlaylistView {
    playlist: PlaylistSummary;
    videos: Array<Video>;
}
export type NotificationKind = {
    __kind__: "newVideo";
    newVideo: {
        channelId: UserId;
        videoId: bigint;
    };
} | {
    __kind__: "newSubscriber";
    newSubscriber: {
        channelId: UserId;
    };
};
export type Cursor = bigint;
export interface User {
    id: UserId;
    bio?: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatar?: ExternalBlob;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Playlist {
    id: bigint;
    title: string;
    ownerId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    isPrivate: boolean;
    videoIds: Array<bigint>;
}
export interface Page_2 {
    items: Array<PlaylistSummary>;
    nextCursor?: Cursor;
}
export interface Page_1 {
    items: Array<Notification>;
    nextCursor?: Cursor;
}
export interface PlaylistSummary {
    id: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    videoCount: bigint;
    firstVideoId?: bigint;
    ownerId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    isPrivate: boolean;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export type UserId = Principal;
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type PlaylistSelection = {
    __kind__: "new";
    new: {
        title: string;
        isPrivate: boolean;
    };
} | {
    __kind__: "existing";
    existing: bigint;
};
export interface Page {
    items: Array<Video>;
    nextCursor?: Cursor;
}
export interface Notification {
    id: bigint;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
    recipientId: UserId;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface CreateVideoResult {
    video: Video;
    playlistId?: bigint;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoStatus {
    deleted = "deleted",
    published = "published",
    processing = "processing",
    draft = "draft"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    addVideoToPlaylist(playlistId: bigint, videoId: bigint): Promise<Playlist>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createPlaylist(title: string, isPrivate: boolean, initialVideoId: bigint | null): Promise<Playlist>;
    createVideo(title: string, description: string | null, video: ExternalBlob, thumbnail: ExternalBlob | null, filename: string, mimeType: string, fileSize: bigint, isPrivate: boolean, playlist: PlaylistSelection | null): Promise<CreateVideoResult>;
    deleteVideo(videoId: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    getApiDoc(): Promise<string>;
    getCallerProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(userId: UserId): Promise<User | null>;
    getChannelByUsername(username: string): Promise<User | null>;
    getChannelPlaylists(userId: UserId, cursor: Cursor, limit: bigint): Promise<Page_2>;
    getChannelVideos(userId: UserId, cursor: Cursor, limit: bigint): Promise<Page>;
    getFeed(cursor: Cursor, limit: bigint): Promise<Page>;
    getMyPlaylists(): Promise<Array<Playlist>>;
    getMyVideos(cursor: Cursor, limit: bigint): Promise<Page>;
    getNotifications(cursor: Cursor, limit: bigint): Promise<Page_1>;
    getPlaylist(playlistId: bigint): Promise<PlaylistView | null>;
    getStorageProviders(): Promise<Array<string>>;
    getSubscribedChannels(): Promise<Array<UserId>>;
    getSubscriberCount(channelId: UserId): Promise<bigint>;
    getSubscriptionFeed(cursor: Cursor, limit: bigint): Promise<Page>;
    getUnreadNotificationCount(): Promise<bigint>;
    getVideo(videoId: bigint): Promise<Video | null>;
    isCallerAdmin(): Promise<boolean>;
    isSubscribed(channelId: UserId): Promise<boolean>;
    markNotificationsRead(): Promise<void>;
    publishVideo(videoId: bigint): Promise<Video>;
    recordVideoView(videoId: bigint): Promise<bigint>;
    registerStorageProvider(providerId: string): Promise<void>;
    removeVideoFromPlaylist(playlistId: bigint, videoId: bigint): Promise<Playlist>;
    saveProfile(displayName: string, username: string, avatar: ExternalBlob | null, removeAvatar: boolean, bio: string | null): Promise<User>;
    schema(): Promise<string>;
    subscribe(channelId: UserId): Promise<void>;
    unsubscribe(channelId: UserId): Promise<void>;
}
import type { Cell as _Cell, CreateVideoResult as _CreateVideoResult, Cursor as _Cursor, Error as _Error, ExternalBlob as _ExternalBlob, Notification as _Notification, NotificationKind as _NotificationKind, Page as _Page, Page_1 as _Page_1, Page_2 as _Page_2, PlaylistSelection as _PlaylistSelection, PlaylistSummary as _PlaylistSummary, PlaylistView as _PlaylistView, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, User as _User, UserId as _UserId, UserRole as _UserRole, Value as _Value, Video as _Video, VideoStatus as _VideoStatus, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addVideoToPlaylist(arg0: bigint, arg1: bigint): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.addVideoToPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addVideoToPlaylist(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n12(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createPlaylist(arg0: string, arg1: boolean, arg2: bigint | null): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.createPlaylist(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPlaylist(arg0, arg1, to_candid_opt_n14(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async createVideo(arg0: string, arg1: string | null, arg2: ExternalBlob, arg3: ExternalBlob | null, arg4: string, arg5: string, arg6: bigint, arg7: boolean, arg8: PlaylistSelection | null): Promise<CreateVideoResult> {
        if (this.processError) {
            try {
                const result = await this.actor.createVideo(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8));
                return from_candid_CreateVideoResult_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createVideo(arg0, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg1), await to_candid_ExternalBlob_n16(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg3), arg4, arg5, arg6, arg7, to_candid_opt_n18(this._uploadFile, this._downloadFile, arg8));
            return from_candid_CreateVideoResult_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelByUsername(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelByUsername(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelByUsername(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelPlaylists(arg0: UserId, arg1: Cursor, arg2: bigint): Promise<Page_2> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelPlaylists(arg0, arg1, arg2);
                return from_candid_Page_2_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelPlaylists(arg0, arg1, arg2);
            return from_candid_Page_2_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelVideos(arg0: UserId, arg1: Cursor, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelVideos(arg0, arg1, arg2);
                return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelVideos(arg0, arg1, arg2);
            return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeed(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyPlaylists(): Promise<Array<Playlist>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyPlaylists();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyPlaylists();
            return result;
        }
    }
    async getMyVideos(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVideos(arg0, arg1);
                return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVideos(arg0, arg1);
            return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Cursor, arg1: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0, arg1);
                return from_candid_Page_1_n53(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0, arg1);
            return from_candid_Page_1_n53(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPlaylist(arg0: bigint): Promise<PlaylistView | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPlaylist(arg0);
                return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPlaylist(arg0);
            return from_candid_opt_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStorageProviders(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorageProviders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorageProviders();
            return result;
        }
    }
    async getSubscribedChannels(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscribedChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscribedChannels();
            return result;
        }
    }
    async getSubscriberCount(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriberCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriberCount(arg0);
            return result;
        }
    }
    async getSubscriptionFeed(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionFeed(arg0, arg1);
                return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionFeed(arg0, arg1);
            return from_candid_Page_n50(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getVideo(arg0: bigint): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSubscribed(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscribed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscribed(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async publishVideo(arg0: bigint): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.publishVideo(arg0);
                return from_candid_Video_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishVideo(arg0);
            return from_candid_Video_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async recordVideoView(arg0: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.recordVideoView(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordVideoView(arg0);
            return result;
        }
    }
    async registerStorageProvider(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStorageProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStorageProvider(arg0);
            return result;
        }
    }
    async removeVideoFromPlaylist(arg0: bigint, arg1: bigint): Promise<Playlist> {
        if (this.processError) {
            try {
                const result = await this.actor.removeVideoFromPlaylist(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeVideoFromPlaylist(arg0, arg1);
            return result;
        }
    }
    async saveProfile(arg0: string, arg1: string, arg2: ExternalBlob | null, arg3: boolean, arg4: string | null): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
                return from_candid_User_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, await to_candid_opt_n17(this._uploadFile, this._downloadFile, arg2), arg3, to_candid_opt_n15(this._uploadFile, this._downloadFile, arg4));
            return from_candid_User_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async subscribe(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0);
            return result;
        }
    }
    async unsubscribe(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribe(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function from_candid_CreateVideoResult_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CreateVideoResult): Promise<CreateVideoResult> {
    return await from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_NotificationKind_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return from_candid_variant_n59(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n57(_uploadFile, _downloadFile, value);
}
function from_candid_Page_1_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_1): Page_1 {
    return from_candid_record_n54(_uploadFile, _downloadFile, value);
}
async function from_candid_Page_2_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_2): Promise<Page_2> {
    return await from_candid_record_n45(_uploadFile, _downloadFile, value);
}
async function from_candid_Page_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Promise<Page> {
    return await from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_PlaylistSummary_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaylistSummary): Promise<PlaylistSummary> {
    return await from_candid_record_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_PlaylistView_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PlaylistView): Promise<PlaylistView> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n43(_uploadFile, _downloadFile, value);
}
async function from_candid_User_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): Promise<User> {
    return await from_candid_record_n41(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Video_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Promise<Video> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): Promise<User | null> {
    return value.length === 0 ? null : await from_candid_User_n40(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cursor]): Cursor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_PlaylistView]): Promise<PlaylistView | null> {
    return value.length === 0 ? null : await from_candid_PlaylistView_n61(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Promise<Video | null> {
    return value.length === 0 ? null : await from_candid_Video_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: _Video;
    playlistId: [] | [bigint];
}): Promise<{
    video: Video;
    playlistId?: bigint;
}> {
    return {
        video: await from_candid_Video_n23(_uploadFile, _downloadFile, value.video),
        playlistId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.playlistId))
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _VideoStatus;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    ownerId: _UserId;
    video: _ExternalBlob;
    createdAt: _Timestamp;
    publishedAt: [] | [_Timestamp];
    mimeType: string;
    description: [] | [string];
    fileSize: bigint;
    filename: string;
    viewCount: bigint;
    isPrivate: boolean;
}): Promise<{
    id: bigint;
    status: VideoStatus;
    title: string;
    thumbnail?: ExternalBlob;
    ownerId: UserId;
    video: ExternalBlob;
    createdAt: Timestamp;
    publishedAt?: Timestamp;
    mimeType: string;
    description?: string;
    fileSize: bigint;
    filename: string;
    viewCount: bigint;
    isPrivate: boolean;
}> {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n25(_uploadFile, _downloadFile, value.status),
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.thumbnail)),
        ownerId: value.ownerId,
        video: await from_candid_ExternalBlob_n28(_uploadFile, _downloadFile, value.video),
        createdAt: value.createdAt,
        publishedAt: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.publishedAt)),
        mimeType: value.mimeType,
        description: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.description)),
        fileSize: value.fileSize,
        filename: value.filename,
        viewCount: value.viewCount,
        isPrivate: value.isPrivate
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n33(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n37(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
async function from_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    username: string;
    displayName: string;
    createdAt: _Timestamp;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    id: UserId;
    bio?: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatar?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.bio)),
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        avatar: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_PlaylistSummary>;
    nextCursor: [] | [_Cursor];
}): Promise<{
    items: Array<PlaylistSummary>;
    nextCursor?: Cursor;
}> {
    return {
        items: await from_candid_vec_n46(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.nextCursor))
    };
}
async function from_candid_record_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    title: string;
    thumbnail: [] | [_ExternalBlob];
    videoCount: bigint;
    firstVideoId: [] | [bigint];
    ownerId: _UserId;
    createdAt: _Timestamp;
    updatedAt: _Timestamp;
    isPrivate: boolean;
}): Promise<{
    id: bigint;
    title: string;
    thumbnail?: ExternalBlob;
    videoCount: bigint;
    firstVideoId?: bigint;
    ownerId: UserId;
    createdAt: Timestamp;
    updatedAt: Timestamp;
    isPrivate: boolean;
}> {
    return {
        id: value.id,
        title: value.title,
        thumbnail: record_opt_to_undefined(await from_candid_opt_n27(_uploadFile, _downloadFile, value.thumbnail)),
        videoCount: value.videoCount,
        firstVideoId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.firstVideoId)),
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        updatedAt: value.updatedAt,
        isPrivate: value.isPrivate
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
async function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_Video>;
    nextCursor: [] | [_Cursor];
}): Promise<{
    items: Array<Video>;
    nextCursor?: Cursor;
}> {
    return {
        items: await from_candid_vec_n52(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_Notification>;
    nextCursor: [] | [_Cursor];
}): {
    items: Array<Notification>;
    nextCursor?: Cursor;
} {
    return {
        items: from_candid_vec_n55(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n49(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _NotificationKind;
    createdAt: _Timestamp;
    read: boolean;
    recipientId: _UserId;
}): {
    id: bigint;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
    recipientId: UserId;
} {
    return {
        id: value.id,
        kind: from_candid_NotificationKind_n58(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        read: value.read,
        recipientId: value.recipientId
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    playlist: _PlaylistSummary;
    videos: Array<_Video>;
}): Promise<{
    playlist: PlaylistSummary;
    videos: Array<Video>;
}> {
    return {
        playlist: await from_candid_PlaylistSummary_n47(_uploadFile, _downloadFile, value.playlist),
        videos: await from_candid_vec_n52(_uploadFile, _downloadFile, value.videos)
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    published: null;
} | {
    processing: null;
} | {
    draft: null;
}): VideoStatus {
    return "deleted" in value ? VideoStatus.deleted : "published" in value ? VideoStatus.published : "processing" in value ? VideoStatus.processing : "draft" in value ? VideoStatus.draft : value;
}
function from_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newVideo: {
        channelId: _UserId;
        videoId: bigint;
    };
} | {
    newSubscriber: {
        channelId: _UserId;
    };
}): {
    __kind__: "newVideo";
    newVideo: {
        channelId: UserId;
        videoId: bigint;
    };
} | {
    __kind__: "newSubscriber";
    newSubscriber: {
        channelId: UserId;
    };
} {
    return "newVideo" in value ? {
        __kind__: "newVideo",
        newVideo: value.newVideo
    } : "newSubscriber" in value ? {
        __kind__: "newSubscriber",
        newSubscriber: value.newSubscriber
    } : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n10(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n35(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PlaylistSummary>): Promise<Array<PlaylistSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PlaylistSummary_n47(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Promise<Array<Video>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Video_n23(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n56(_uploadFile, _downloadFile, x));
}
async function to_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_PlaylistSelection_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistSelection): _PlaylistSelection {
    return to_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: bigint | null): [] | [bigint] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaylistSelection | null): [] | [_PlaylistSelection] {
    return value === null ? candid_none() : candid_some(to_candid_PlaylistSelection_n19(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
function to_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "new";
    new: {
        title: string;
        isPrivate: boolean;
    };
} | {
    __kind__: "existing";
    existing: bigint;
}): {
    new: {
        title: string;
        isPrivate: boolean;
    };
} | {
    existing: bigint;
} {
    return value.__kind__ === "new" ? {
        new: value.new
    } : value.__kind__ === "existing" ? {
        existing: value.existing
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
