/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.2.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Video {
    id: bigint;
    status: VideoStatus;
    title: string;
    ownerId: UserId;
    createdAt: Timestamp;
    videoAssetId: string;
    publishedAt?: Timestamp;
    mimeType: string;
    description?: string;
    fileSize: bigint;
    thumbnailAssetId?: string;
}
export type Timestamp = bigint;
export type Cursor = bigint;
export type NotificationKind = {
    __kind__: "newVideo";
    newVideo: {
        channelId: UserId;
        videoId: bigint;
    };
} | {
    __kind__: "newSubscriber";
    newSubscriber: {
        channelId: UserId;
    };
};
export interface User {
    id: UserId;
    bio?: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatar?: string;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface Page_1 {
    items: Array<Notification>;
    nextCursor?: Cursor;
}
export type UserId = Principal;
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export interface Page {
    items: Array<Video>;
    nextCursor?: Cursor;
}
export interface UploadSession {
    id: bigint;
    status: UploadStatus;
    ownerId: UserId;
    assetId: string;
    kind: UploadKind;
    createdAt: Timestamp;
    receivedBytes: bigint;
    mimeType: string;
    totalSize: bigint;
    chunkSize: bigint;
}
export interface Notification {
    id: bigint;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
    recipientId: UserId;
}
export interface Cell {
    value: Value;
    name: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum UploadKind {
    thumbnail = "thumbnail",
    video = "video"
}
export enum UploadStatus {
    active = "active",
    cancelled = "cancelled",
    completed = "completed",
    finalized = "finalized"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum VideoStatus {
    deleted = "deleted",
    published = "published",
    processing = "processing",
    draft = "draft"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createUploadSession(kind: UploadKind, totalSize: bigint, mimeType: string): Promise<UploadSession>;
    deleteVideo(videoId: bigint): Promise<void>;
    execute(qJson: string): Promise<Result>;
    finalizeMedia(sessionId: bigint, title: string, description: string | null, thumbnailAssetId: string | null): Promise<Video>;
    getApiDoc(): Promise<string>;
    getCallerProfile(): Promise<User | null>;
    getCallerUserRole(): Promise<UserRole>;
    getChannel(userId: UserId): Promise<User | null>;
    getChannelByUsername(username: string): Promise<User | null>;
    getChannelVideos(userId: UserId, cursor: Cursor, limit: bigint): Promise<Page>;
    getFeed(cursor: Cursor, limit: bigint): Promise<Page>;
    getMyVideos(cursor: Cursor, limit: bigint): Promise<Page>;
    getNotifications(cursor: Cursor, limit: bigint): Promise<Page_1>;
    getStorageProviders(): Promise<Array<string>>;
    getSubscribedChannels(): Promise<Array<UserId>>;
    getSubscriberCount(channelId: UserId): Promise<bigint>;
    getSubscriptionFeed(cursor: Cursor, limit: bigint): Promise<Page>;
    getUnreadNotificationCount(): Promise<bigint>;
    getVideo(videoId: bigint): Promise<Video | null>;
    isCallerAdmin(): Promise<boolean>;
    isSubscribed(channelId: UserId): Promise<boolean>;
    markNotificationsRead(): Promise<void>;
    publishVideo(videoId: bigint): Promise<Video>;
    registerStorageProvider(providerId: string): Promise<void>;
    saveProfile(displayName: string, username: string, avatar: string | null, bio: string | null): Promise<User>;
    schema(): Promise<string>;
    subscribe(channelId: UserId): Promise<void>;
    unsubscribe(channelId: UserId): Promise<void>;
    uploadChunk(sessionId: bigint, chunkIndex: bigint, data: Uint8Array): Promise<bigint>;
    verifyUpload(sessionId: bigint): Promise<void>;
}
import type { Cell as _Cell, Cursor as _Cursor, Error as _Error, Notification as _Notification, NotificationKind as _NotificationKind, Page as _Page, Page_1 as _Page_1, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UploadKind as _UploadKind, UploadSession as _UploadSession, UploadStatus as _UploadStatus, User as _User, UserId as _UserId, UserRole as _UserRole, Value as _Value, Video as _Video, VideoStatus as _VideoStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createUploadSession(arg0: UploadKind, arg1: bigint, arg2: string): Promise<UploadSession> {
        if (this.processError) {
            try {
                const result = await this.actor.createUploadSession(to_candid_UploadKind_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_UploadSession_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createUploadSession(to_candid_UploadKind_n7(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_UploadSession_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteVideo(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteVideo(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteVideo(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async finalizeMedia(arg0: bigint, arg1: string, arg2: string | null, arg3: string | null): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.finalizeMedia(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return from_candid_Video_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.finalizeMedia(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return from_candid_Video_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerProfile(): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerProfile();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerProfile();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannel(arg0: UserId): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannel(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannel(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelByUsername(arg0: string): Promise<User | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelByUsername(arg0);
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelByUsername(arg0);
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getChannelVideos(arg0: UserId, arg1: Cursor, arg2: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getChannelVideos(arg0, arg1, arg2);
                return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getChannelVideos(arg0, arg1, arg2);
            return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFeed(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getFeed(arg0, arg1);
                return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFeed(arg0, arg1);
            return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyVideos(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyVideos(arg0, arg1);
                return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyVideos(arg0, arg1);
            return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(arg0: Cursor, arg1: bigint): Promise<Page_1> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications(arg0, arg1);
                return from_candid_Page_1_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications(arg0, arg1);
            return from_candid_Page_1_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStorageProviders(): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStorageProviders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStorageProviders();
            return result;
        }
    }
    async getSubscribedChannels(): Promise<Array<UserId>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscribedChannels();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscribedChannels();
            return result;
        }
    }
    async getSubscriberCount(arg0: UserId): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriberCount(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriberCount(arg0);
            return result;
        }
    }
    async getSubscriptionFeed(arg0: Cursor, arg1: bigint): Promise<Page> {
        if (this.processError) {
            try {
                const result = await this.actor.getSubscriptionFeed(arg0, arg1);
                return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSubscriptionFeed(arg0, arg1);
            return from_candid_Page_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUnreadNotificationCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadNotificationCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadNotificationCount();
            return result;
        }
    }
    async getVideo(arg0: bigint): Promise<Video | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getVideo(arg0);
                return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getVideo(arg0);
            return from_candid_opt_n46(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isSubscribed(arg0: UserId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isSubscribed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isSubscribed(arg0);
            return result;
        }
    }
    async markNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationsRead();
            return result;
        }
    }
    async publishVideo(arg0: bigint): Promise<Video> {
        if (this.processError) {
            try {
                const result = await this.actor.publishVideo(arg0);
                return from_candid_Video_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishVideo(arg0);
            return from_candid_Video_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerStorageProvider(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerStorageProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerStorageProvider(arg0);
            return result;
        }
    }
    async saveProfile(arg0: string, arg1: string, arg2: string | null, arg3: string | null): Promise<User> {
        if (this.processError) {
            try {
                const result = await this.actor.saveProfile(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
                return from_candid_User_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveProfile(arg0, arg1, to_candid_opt_n23(this._uploadFile, this._downloadFile, arg2), to_candid_opt_n23(this._uploadFile, this._downloadFile, arg3));
            return from_candid_User_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async subscribe(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.subscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.subscribe(arg0);
            return result;
        }
    }
    async unsubscribe(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unsubscribe(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unsubscribe(arg0);
            return result;
        }
    }
    async uploadChunk(arg0: bigint, arg1: bigint, arg2: Uint8Array): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadChunk(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadChunk(arg0, arg1, arg2);
            return result;
        }
    }
    async verifyUpload(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyUpload(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyUpload(arg0);
            return result;
        }
    }
}
function from_candid_Cell_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_NotificationKind_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotificationKind): NotificationKind {
    return from_candid_variant_n45(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n43(_uploadFile, _downloadFile, value);
}
function from_candid_Page_1_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page_1): Page_1 {
    return from_candid_record_n40(_uploadFile, _downloadFile, value);
}
function from_candid_Page_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Page): Page {
    return from_candid_record_n36(_uploadFile, _downloadFile, value);
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_UploadKind_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadKind): UploadKind {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UploadSession_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadSession): UploadSession {
    return from_candid_record_n10(_uploadFile, _downloadFile, value);
}
function from_candid_UploadStatus_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UploadStatus): UploadStatus {
    return from_candid_variant_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n34(_uploadFile, _downloadFile, value);
}
function from_candid_User_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _User): User {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Value_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_VideoStatus_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _VideoStatus): VideoStatus {
    return from_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function from_candid_Video_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Video): Video {
    return from_candid_record_n25(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_User]): User | null {
    return value.length === 0 ? null : from_candid_User_n31(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Cursor]): Cursor | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Video]): Video | null {
    return value.length === 0 ? null : from_candid_Video_n24(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _UploadStatus;
    ownerId: _UserId;
    assetId: string;
    kind: _UploadKind;
    createdAt: _Timestamp;
    receivedBytes: bigint;
    mimeType: string;
    totalSize: bigint;
    chunkSize: bigint;
}): {
    id: bigint;
    status: UploadStatus;
    ownerId: UserId;
    assetId: string;
    kind: UploadKind;
    createdAt: Timestamp;
    receivedBytes: bigint;
    mimeType: string;
    totalSize: bigint;
    chunkSize: bigint;
} {
    return {
        id: value.id,
        status: from_candid_UploadStatus_n11(_uploadFile, _downloadFile, value.status),
        ownerId: value.ownerId,
        assetId: value.assetId,
        kind: from_candid_UploadKind_n13(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        receivedBytes: value.receivedBytes,
        mimeType: value.mimeType,
        totalSize: value.totalSize,
        chunkSize: value.chunkSize
    };
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n17(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n21(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _VideoStatus;
    title: string;
    ownerId: _UserId;
    createdAt: _Timestamp;
    videoAssetId: string;
    publishedAt: [] | [_Timestamp];
    mimeType: string;
    description: [] | [string];
    fileSize: bigint;
    thumbnailAssetId: [] | [string];
}): {
    id: bigint;
    status: VideoStatus;
    title: string;
    ownerId: UserId;
    createdAt: Timestamp;
    videoAssetId: string;
    publishedAt?: Timestamp;
    mimeType: string;
    description?: string;
    fileSize: bigint;
    thumbnailAssetId?: string;
} {
    return {
        id: value.id,
        status: from_candid_VideoStatus_n26(_uploadFile, _downloadFile, value.status),
        title: value.title,
        ownerId: value.ownerId,
        createdAt: value.createdAt,
        videoAssetId: value.videoAssetId,
        publishedAt: record_opt_to_undefined(from_candid_opt_n28(_uploadFile, _downloadFile, value.publishedAt)),
        mimeType: value.mimeType,
        description: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.description)),
        fileSize: value.fileSize,
        thumbnailAssetId: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.thumbnailAssetId))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    username: string;
    displayName: string;
    createdAt: _Timestamp;
    avatar: [] | [string];
}): {
    id: UserId;
    bio?: string;
    username: string;
    displayName: string;
    createdAt: Timestamp;
    avatar?: string;
} {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.bio)),
        username: value.username,
        displayName: value.displayName,
        createdAt: value.createdAt,
        avatar: record_opt_to_undefined(from_candid_opt_n29(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_Video>;
    nextCursor: [] | [_Cursor];
}): {
    items: Array<Video>;
    nextCursor?: Cursor;
} {
    return {
        items: from_candid_vec_n37(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    items: Array<_Notification>;
    nextCursor: [] | [_Cursor];
}): {
    items: Array<Notification>;
    nextCursor?: Cursor;
} {
    return {
        items: from_candid_vec_n41(_uploadFile, _downloadFile, value.items),
        nextCursor: record_opt_to_undefined(from_candid_opt_n38(_uploadFile, _downloadFile, value.nextCursor))
    };
}
function from_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    kind: _NotificationKind;
    createdAt: _Timestamp;
    read: boolean;
    recipientId: _UserId;
}): {
    id: bigint;
    kind: NotificationKind;
    createdAt: Timestamp;
    read: boolean;
    recipientId: UserId;
} {
    return {
        id: value.id,
        kind: from_candid_NotificationKind_n44(_uploadFile, _downloadFile, value.kind),
        createdAt: value.createdAt,
        read: value.read,
        recipientId: value.recipientId
    };
}
function from_candid_variant_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    finalized: null;
}): UploadStatus {
    return "active" in value ? UploadStatus.active : "cancelled" in value ? UploadStatus.cancelled : "completed" in value ? UploadStatus.completed : "finalized" in value ? UploadStatus.finalized : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    thumbnail: null;
} | {
    video: null;
}): UploadKind {
    return "thumbnail" in value ? UploadKind.thumbnail : "video" in value ? UploadKind.video : value;
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    published: null;
} | {
    processing: null;
} | {
    draft: null;
}): VideoStatus {
    return "deleted" in value ? VideoStatus.deleted : "published" in value ? VideoStatus.published : "processing" in value ? VideoStatus.processing : "draft" in value ? VideoStatus.draft : value;
}
function from_candid_variant_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    newVideo: {
        channelId: _UserId;
        videoId: bigint;
    };
} | {
    newSubscriber: {
        channelId: _UserId;
    };
}): {
    __kind__: "newVideo";
    newVideo: {
        channelId: UserId;
        videoId: bigint;
    };
} | {
    __kind__: "newSubscriber";
    newSubscriber: {
        channelId: UserId;
    };
} {
    return "newVideo" in value ? {
        __kind__: "newVideo",
        newVideo: value.newVideo
    } : "newSubscriber" in value ? {
        __kind__: "newSubscriber",
        newSubscriber: value.newSubscriber
    } : value;
}
function from_candid_vec_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n18(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n19(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Video>): Array<Video> {
    return value.map((x)=>from_candid_Video_n24(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n42(_uploadFile, _downloadFile, x));
}
function to_candid_UploadKind_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadKind): _UploadKind {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UploadKind): {
    thumbnail: null;
} | {
    video: null;
} {
    return value == UploadKind.thumbnail ? {
        thumbnail: null
    } : value == UploadKind.video ? {
        video: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
